version: "3.8"
services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ordersdb
    ports:
      - "5432:5432"

  order.api:
    build:
      context: .
      dockerfile: OrderService.API/Dockerfile
    depends_on:
      - rabbitmq
      - postgres
    environment:
      - POSTGRES_CONN=Host=postgres;Database=ordersdb;Username=postgres;Password=password
      - RABBITMQ__HOST=rabbitmq
      - RABBITMQ__USER=guest
      - RABBITMQ__PASS=guest
    ports:
      - "5000:80"

  order.consumer:
    build:
      context: .
      dockerfile: OrderService.Consumer/Dockerfile
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ__HOST=rabbitmq
      - RABBITMQ__USER=guest
      - RABBITMQ__PASS=guest
